Consistent process test procedure paths
qualicen/specmate pull request #108
Opened 2020-02-28 11:41 UTC by sebeder

[Trello Card](https://trello.com/c/tsMEvsdY/585-testgenerierung-konsistente-ber%C3%BCcksichtigung-von-bedingungen)

2020-03-02 16:44 UTC, junkerm requested changes
It looks good. I did two test models and got the expected results.
![grafik](https://user-images.githubusercontent.com/8638706/75695268-1a14fc00-5caa-11ea-9919-b2ee81203b59.png)
![grafik](https://user-images.githubusercontent.com/8638706/75695302-2600be00-5caa-11ea-8425-7442d92b2f88.png)

Could you adapt the unit tests so that they run and capture the additional contstraints?

2020-03-02 16:44 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/ProcessTestCaseGenerator.java
> +				.flatMap(g -> g.getEdgeList().stream())
rename g to path to make clear you are iterating over paths

2020-03-02 16:44 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/ProcessTestCaseGenerator.java
> +	private static boolean hasCondition(IModelNode node, String condition) {
There is also a non-static hasCondition method, I find this a bit confusing to have static and non-static methods with the same name in different places in the file

2020-03-02 16:44 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/ProcessTestCaseGenerator.java
> +	private DirectedGraph<IModelNode, ProcessConnection> getGraph(String condition) {
could you pick a method name that is more descriptive of what is going on?

2020-03-10 06:57 UTC, sebeder commented
Hi @junkerm ! I adressed your comments. Would you review it again? Thank!

2020-03-10 14:48 UTC, junkerm approved these changes
tests look good!

2020-03-10 17:37 UTC, merged