First version of linked node tool
qualicen/specmate pull request #157
Opened 2020-09-23 15:11 UTC by sebeder

[Trello Card](https://trello.com/c/UQWuNoAd/700-kapselung-werkzeug-f%C3%BCr-verlinkenden-knoten)

This one only includes the new tool. The nodes itself are useless right now.

2020-09-23 19:10 UTC, wehrlean requested changes
Good. Only small code-style changes

2020-09-23 19:10 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/vertex-provider.ts
> +        const l1 = this.graph.insertVertex(vertex, url + VertexProvider.ID_SUFFIX_VARIABLE, data.variable,
l1 is no good name

2020-09-23 19:10 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/tool-pallette/tools/ceg/ceg-linked-node-tool.ts
> +    public style = new ShapeProvider(CEGModel).getStyle(CEGLinkedNode);
In web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/vertex-provider.ts it is getStyle(new CEGLinkedNode()) here only getStyle(CEGLinkedNode);
Does both work? We should do it the same way.

2020-09-23 19:10 UTC, wehrlean commented on web/src/app/validation/ceg/node-cycle-validator.ts
> +    private nodes: (CEGNode|CEGLinkedNode)[];
Spaces

2020-09-24 07:29 UTC, sebeder commented on web/src/app/modules/views/main/editors/modules/tool-pallette/tools/ceg/ceg-linked-node-tool.ts
> +    public style = new ShapeProvider(CEGModel).getStyle(CEGLinkedNode);
I changed the other place and removed the constructor call.

2020-09-24 07:29 UTC, sebeder commented on web/src/app/validation/ceg/node-cycle-validator.ts
> +    private nodes: (CEGNode|CEGLinkedNode)[];
Done

2020-09-24 07:29 UTC, sebeder commented on web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/vertex-provider.ts
> +        const l1 = this.graph.insertVertex(vertex, url + VertexProvider.ID_SUFFIX_VARIABLE, data.variable,
I changed the name to `nameVertex`.

2020-09-24 07:59 UTC, wehrlean approved these changes

2020-09-24 08:09 UTC, merged