Link models linked node appearance
qualicen/specmate pull request #166
Opened 2020-10-06 13:31 UTC by sebeder

[Trello Card](https://trello.com/c/m5T8PfWo/662-kapselung-optische-darstellung-verlinkter-knoten)

2020-10-06 14:10 UTC, wehrlean requested changes
With double clicking the text is still editable

2020-10-06 14:24 UTC, wehrlean requested changes

2020-10-06 14:24 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/vertex-provider.ts
> +        const vertexSymbol = this.graph.insertVertex(vertex, url + VertexProvider.ID_SUFFIX_CONDITION, '🔗',
VertexProvider.ID_SUFFIX_CONDITION is not correct

2020-10-07 06:45 UTC, sebeder commented
OMG! I'll resolve the issues now... Coding in the bus is not my strength, obviously.

2020-10-07 09:24 UTC, wehrlean commented
> 
> 
>     1. With double clicking the text is still editable
> 
>     2. And if you rest with the cursor on the 🔗 symbol, you get a hint with the same symbol. No direct error but not necessary
> 
>     3. On reload, the nodes are small and on the left top corner
>        ![image](https://user-images.githubusercontent.com/49229000/95213618-4c15b000-07ef-11eb-8b0d-327bf3a37c38.png)

Still all point not solved

2020-10-07 12:51 UTC, sebeder commented
Should work now... Was a little bit harder than it seemed.

2020-10-08 09:40 UTC, wehrlean approved these changes
Now everything is fine :)

2020-10-08 09:41 UTC, merged