Dokumentation julia
qualicen/specmate pull request #172
Opened 2020-10-30 14:19 UTC by TimmJulia

[Trello Card]()

2020-12-11 09:05 UTC, junkerm requested changes
Siehe meine Kommentare - bisher habe ich nur index_JuliasVersion.md  durchgescahtu

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +* Stellen Sie sicher, dass Java 1.8 installiert ist. Wenn nicht, besorgen Sie sich ein Java 1.8 Release, z.B. von [hier](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-213315
Muss jetzt Java 11 sein, und der Link zu oracle stattdessen https://adoptopenjdk.net/

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +* Besorgen Sie sich die neueste Version von Specmate auf der Download-Seite. Wo und wie Sie die Datei herunterladen, lesen Sie im nächsten Abschnitt *Konfiguration*.
Von der Download Seite gibt es jetzt eine Zip Datei, die man entpacken muss und dann die specmate.bat  bzw. die specmate.sh starten. In der Zip Datei ist schon eine specmate-config.properties die man nur noch anpassen muss, d.h. den Link zur Beispiel config braucht es gar nicht mehr

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +* Besorgen Sie sich die neueste Version von Specmate auf der Download-Seite. Wo und wie Sie die Datei herunterladen, lesen Sie im nächsten Abschnitt *Konfiguration*.
Im Abschnitt Konfiguration steht nichts wo und wie man das runterlädt

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +``properties java -jar specmate.jar --configurationFile [Pfad-zu-ihrer-config-file]```
hier auch: einfach nur die specmate.bat (windows) bzw. specmate.sh (linux/mac) starnten

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Nach dem Aufruf von Specmate wird Ihnen die Anmeldeseite angezeigt. Bitte geben Sie hier einen Benutzernamen, ein Passwort und ein Specmate-Projekt ein. Für die Verwendung von Specmate benötigen Sie
Ich würde das hier ohnehin auf Jira münzen. Vorschlag: In dem Kapitel Konfiguration oben machen wir eine Beispielkonfiguration für Jira rein. Dann können wir hier beim Login sagen: Melde dich in Jira an.

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Nach dem Aufruf von Specmate wird Ihnen die Anmeldeseite angezeigt. Bitte geben Sie hier einen Benutzernamen, ein Passwort und ein Specmate-Projekt ein. Für die Verwendung von Specmate benötigen Sie
Die Referenz auf Allianz muss noch raus

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +- Im Projekt-Explorer können Sie zwischen der *Projekt*ansicht mit den importierten Anforderungen und der *Bibliotheks*ansicht wechseln. In der Projektansicht werden nur die Anforderungen und die daz
evtl. missverständlich, vielleicht besser: ... in der Projektansicht ist die Ordnerstruktur durch den Anforderungs-Import vorgegeben, es können keine ....

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +- Im oberen Teil des Bildschirms auf der rechten Seite sehen Sie die aktuelle Specmate-Version. Daneben können Sie wählen, ob der Log ein- oder ausgeblendet werden soll, Sie können die Sprache wählen
Log -> "Ereignisprotokoll"?

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +- Specmate zeigt erst dann passende Suchergebnisse, wenn Sie mindestens drei Zeichen in das Suchfeld eingegeben haben.
hat sich geändert: Sind jetzt zwei Zeichen ;-)

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +- Specmate unterstützt auch *Wildcard-Suchen*, nämlich
Kannst du das nochmal in der letzten version (0.4.1-rc-10 checken?) Da hat sich bei der Suche bisschen was getan

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +1. einen oder mehrere Knoten zu setzen.
zu setzen -> per Drag&Drop hinzuzufügen?

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +3. die Hilfslinien auszublenden.
ein-/ und auszublenden

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Klicken Sie auf den Text "Knoten", wie im Bild gezeigt, und ziehen Sie den Text "Knoten" in das mit Hilfslinien versehene Editor-Feld. Der so gesetzte Knoten (respektive die Variable) erscheint hier
(respektive die Variable) würde ich löschen

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Ist Ihre Verbindung z. B. fälschlicherweise negiert, zeigt sich eine Fehlermeldung direkt an der Verbindung. Für alle Fehlermeldungen, die durch ein dreieckig gerahmtes Ausrufezeichen visualisiert we
was meinst du mit "fälschlicherweise negiert"?

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Löschen können Sie Verbindungen und Knoten über die Entfernen-Taste (Windows) oder indem Sie die Command- und die Löschen-Taste (OS) gleichzeitig betätigen. Oder Sie klicken die Verbindung mit der re
Vorschlag: Windows -> Windows-Tastatur, OS -> Mac Tastatur

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Mit `Strg + C` kopieren Sie den Bereich. Das kopierte Modell kann im gleichen oder in anderen Editoren mit `Strg + V` wieder eingefügt und weiter bearbeitet werden.
Oben hattest du immer noch die Mac Version angegeben, evtl. hier auch?

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +## Ursache-Wirkungs-Diagramme (Cause-Effect-Graphs CEGs)
ich bin jetzt verwirrt: Oben war ja schon Ursache-Wirkungs-Modellierung und jetzt kommt es hier wieder. Einige Dinge hier sind auch redundant zu oben, z.B. wie man verbindugnen zieht. Evtl. in einen Abschnitt zusammenführen oder oben ggf. Details auslassen und zu diesem Abschnitt verweisen?

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +indem man vor die Bedingung ein '=' setzt. Damit weiß Specmate, dass nur eine Bedingung der Variable wahr sein kann.
Damit weiß Specmate --> Damit teilen Sie Specmate mit, dass

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Variablennamen haben und bei denen die Bedingung mit = gesetzt ist, jeweils nur ein Knoten gleichzeitig wahr ist.
nur ein Knoten   --> immer genau ein Knoten

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Andere Beispiele für Zustände finden Sie in unserem [Tutorial](Tutorial).
Link fehlt --> evtl. einfach rauslassen

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Um zwei Elemente zu verbinden, müssen Sie das Werkzeug [*Verbindung*](#verbindung) und die Knoten auswählen, die Sie verbinden möchten. Für jede Verbindung können Sie eine Bedingung setzen, die der v
Das Werkzeug "Verbindung" gibt es nicht mehr

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Trifft eines oder mehrere dieser Szenarien für Ihr Prozessmodell zu, beheben Sie die Fehlerquelle und drücken Sie auf den Validieren-Button.
Prozessmodell --> CEG Modell

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Nutzen Sie im Modell-Editor die Option "Testspezifikation generieren" auf der rechten Seite im Reiter "Links & Actions", um eine Testspezifikation aus einem Modell zu erzeugen. Alternativ finden Sie
Reiter --> Abschnitt (zumindest versehe ich unter reiter immer so tabs die sich oben nebeneinander befinden

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Nutzen Sie im Modell-Editor die Option "Testspezifikation generieren" auf der rechten Seite im Reiter "Links & Actions", um eine Testspezifikation aus einem Modell zu erzeugen. Alternativ finden Sie
Die Option Testspezifikation generieren gibt es in der Anforderungsübersicht nicht mehr

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Die Spezifikation besteht aus mehreren Testfällen, wobei jeder Testfall eine bestimmte Konfiguration hat. Ein Testfall weist jeder Variable einen Wert zu. In bestimmten Testfällen lässt Specmate den
Verweis zu Liggesmeyer würde ich rausnehmen

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Es kann vorkommen, dass inkonsistente Tests erzeugt werden, die gegen die sog. *Liggesmeyer-Regeln* verstoßen. Oder, dass das Modell auf eine andere Art widersprüchlich ist. Zum Beispiel, da sich die
auch hier: Verweis auf Liggesmeyer würde ich rausnehmen

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +--> BILD ANPASSEN!!! SO NICHT SINNVOL!
noch zu machen oder?

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +
wenn ein nötiger Testfall (z.B. auf Grund der Beschränkungen durch den "=") Operator nicht möglich ist, wird er rot dargestellt

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Aus jedem Testfall können Sie eine Testprozedur anlegen. Hier können Sie alle notwendigen Schritte für den jeweiligen Testfall definieren. Bei der Modellierung eines CEG muss die Testprozedur manuell
Aus jedem --> Für jeden

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Aus jedem Testfall können Sie eine Testprozedur anlegen. Hier können Sie alle notwendigen Schritte für den jeweiligen Testfall definieren. Bei der Modellierung eines CEG muss die Testprozedur manuell
Namen und Beschreibungen können nach ALM exportiert werden --> Testprozeduren können (wie auch Testspezifikationen) exportiert werden

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Specmate ermöglicht den Export von Testprozeduren nach HP ALM, wenn der Export für das Projekt aktiviert wurde. Aktuell ist der HP ALM Export nur für das Projekt „ppm“ aktiviert.
ich würde hier einfach schreiben: Specmate unterstützt den Export nach Atlassian Jira, sowie XRay.

Gilt für das ganze Dokument: PPM und ALM überall rausnehmen

2020-12-11 09:05 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +In HP ALM ist die exportierte Testprozedur anschließend im Abschnitt *Test Plan*
Diesen Punkt und die drunter einfach rausnehmen

2020-12-11 12:41 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +* Stellen Sie sicher, dass Java 1.8 installiert ist. Wenn nicht, besorgen Sie sich ein Java 1.8 Release, z.B. von [hier](https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-213315
@junkerm so ein quatsch

2020-12-11 13:01 UTC, TimmJulia commented on documentation/index_JuliasVersion.md
> +
zusätzlicher Punkt von Maxi

2020-12-11 13:09 UTC, TimmJulia commented on documentation/index_JuliasVersion.md
> +Ist Ihre Verbindung z. B. fälschlicherweise negiert, zeigt sich eine Fehlermeldung direkt an der Verbindung. Für alle Fehlermeldungen, die durch ein dreieckig gerahmtes Ausrufezeichen visualisiert we
lieber "Gibt es einen Knoten ohne Verbindung z.B...."

2020-12-11 13:12 UTC, TimmJulia commented on documentation/index_JuliasVersion.md
> +## Ursache-Wirkungs-Diagramme (Cause-Effect-Graphs CEGs)
evtl. lieber verlinken statt doppeln

2020-12-11 13:13 UTC, TimmJulia commented on documentation/index_JuliasVersion.md
> +Trifft eines oder mehrere dieser Szenarien für Ihr Prozessmodell zu, beheben Sie die Fehlerquelle und drücken Sie auf den Validieren-Button.
copy paste Fehler?!

2020-12-11 13:14 UTC, TimmJulia commented on documentation/index_JuliasVersion.md
> +Die Spezifikation besteht aus mehreren Testfällen, wobei jeder Testfall eine bestimmte Konfiguration hat. Ein Testfall weist jeder Variable einen Wert zu. In bestimmten Testfällen lässt Specmate den
neutraler Formulieren und nicht nach Lig. benennen!

2021-01-15 10:43 UTC, junkerm approved these changes, later dismissed
Aus meiner Sicht passt das, mir sind nur noch ein paar Kleinigkeiten aufgefallen

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +* Stellen Sie sicher, dass Java 11 installiert ist. Wenn nicht, besorgen Sie es sich z.B. von [hier](https://adoptopenjdk.net/). Um herauszufinden, welche Java-Version Sie gerade verwenden, geben Sie
Vielleicht noch einen Link auf die Download Seite angeben?

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Wenn Sie Specmate für Ihr Jira-Projekt verwenden wollen, loggen Sie sich bei Jira ein. Unten rechts auf Ihrer Projekt-Seite sehen Sie Specmate und ein Dropdown-Menü. Wenn Sie auf dieses klicken, ersc
Das konkrete Projekt in Specmate kann auch anders heißen, je nachdem welcher Name in Specmate konfiguriert ist. Das bei uns das Specmate-Projekt auch "jira" heißt ist nur Zufall. Man muss also quasi wissen, dass das Specmate Projekt xyz ein Jira Projekt ist und man sich mit seinen Jira zugangsdaten anmelden kann. Guter Punkt- wenn ich drüber nachdenke wäre es nicht schlecht, das irgendwie in der UI anzuzeigen, z.B. mit einem Jira Logo...

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Melden Sie sich bei Specmate mit Ihren Zugangsdaten für Jira an und wählen Sie beim Dropdown-Menü "Projekt" Jira aus.
siehe kommentar oben

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +In diesem Abschnitt lernen Sie die grundlegenden Editorfunktionen sowohl für CEG- als auch für Prozessmodelle kennen.
Finde ich super so! :-)

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Wenn Sie mehrere Verbindungen und/oder Knoten auswählen wollen, weil Sie z.B. einen Teil Ihres Modells kopieren und/oder in der Bibliothek abspeichern wollen, halten Sie die Strg-Taste (Windows) oder
OS -> MacOS (?)

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Es kann vorkommen, dass inkonsistente Tests erzeugt werden, die gegen Regeln verstoßen. Oder, dass das Modell auf eine andere Art widersprüchlich ist. Zum Beispiel, da sich die Bedingungen der Variab
die gegen Regeln verstoßen  --> bei denen Specmate nicht alle Testerzeugungsregeln erfüllen konnte

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +
passt!

2021-01-15 10:43 UTC, junkerm commented on documentation/index_JuliasVersion.md
> +Wenn die Erstellung einer Testprozedur abgeschlossen ist, können Sie sie mit der Schaltfläche *Testprozedur exportieren* auf der rechten Seite z.B. nach Jira XRay Cloud exportieren und sie dort weite
ist das so, das specmate vorher frägt? Mir ist neulich aufgefallen dass er nicth gefragt hat. Evtl. ist das auch ein bug

2021-04-16 11:14 UTC, junkerm approved these changes

2021-04-16 11:32 UTC, merged