Migrator for linking models
qualicen/specmate pull request #173
Opened 2020-11-03 10:51 UTC by wehrlean

[Trello Card](https://trello.com/c/PAZWm3jo/701-kapselung-migrator-schreiben)

2020-11-27 12:43 UTC, junkerm requested changes
Please also add tests to the migration test package

2020-11-27 12:43 UTC, junkerm commented on bundles/specmate-dbprovider-api/src/com/specmate/dbprovider/api/migration/IAttributeToSQLMapper.java
>  	void migrateNewObjectReference(String objectName, String attributeName) throws SpecmateException;
what multiplicity is this migrationcode doing? please change the method name accordingly to be consistent

2020-11-27 12:43 UTC, junkerm commented on bundles/specmate-dbprovider-h2/src/specmate/dbprovider/h2/AttributeToSQLMapper.java
> +	public void migrateNewObjectReferenceOneToN(String objectName, String attributeName) throws SpecmateException {
please add this to the oracle version as well

2021-01-03 10:41 UTC, junkerm commented
@wehrlean I fixed the issues and added tests - could you do a review?

2021-01-11 14:09 UTC, wehrlean commented
It works perfect on my computer. Tests pass local. Travis is at the moment not available, but I think we can merge it.

2021-01-22 08:46 UTC, wehrlean commented
@junkerm Kann man mergen, oder?

2021-01-22 09:10 UTC, merged