Delete the modelImage if model is empty. Additional refactor specmate-typechecking
qualicen/specmate pull request #182
Opened 2020-11-16 14:53 UTC by wehrlean

[Trello Card](https://trello.com/c/MVGGR8nW/693-modellbild-l%C3%B6schen-wenn-modell-keine-elemente-enth%C3%A4lt)

Aditionally, I refactor the checking for models.

2020-11-16 14:54 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/services/model-image.service.ts
>  import { Process } from 'src/app/model/Process';
This is the class with the 'real' changes

2020-11-17 05:58 UTC, sebeder requested changes

2020-11-17 05:58 UTC, sebeder commented on web/src/app/util/specmateType.ts
> +import { CEGConnection } from '../model/CEGConnection';
The filename should be `specmate-type.ts`

2020-11-17 10:42 UTC, sebeder approved these changes

2020-11-18 09:18 UTC, merged