added function to get list of all (accessible) jira projects.
qualicen/specmate pull request #234
Opened 2021-01-13 14:28 UTC by hauptmab

Closes #196

2021-01-18 08:01 UTC, junkerm requested changes

2021-01-18 08:01 UTC, junkerm commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraUtil.java
> +			throw new SpecmateAuthorizationException("Jira authentication failed.", e);
please add a finally block and close the client

2021-01-18 08:01 UTC, junkerm commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraUtil.java
> +		} catch (Exception e) {
please be more specific which exception you catch and throw (you can also use SpecmateInternalException with a specified error code

2021-01-18 08:01 UTC, junkerm commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraUtil.java
> +	public static List<String> getProjects(String serverUrl, String username, String password)
please use auto format

2021-01-18 16:31 UTC, hauptmab commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraUtil.java
> +			throw new SpecmateAuthorizationException("Jira authentication failed.", e);
improved exception handling

2021-01-18 16:31 UTC, hauptmab commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraUtil.java
> +		} catch (Exception e) {
changed exception handling types

2021-01-18 16:32 UTC, hauptmab commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraUtil.java
> +	public static List<String> getProjects(String serverUrl, String username, String password)
done

2021-01-22 14:53 UTC, junkerm approved these changes

2021-01-27 07:35 UTC, hauptmab commented
This pull request has been part of using https://github.com/qualicen/specmate/pull/236

2021-01-27 07:35 UTC, closed without merging