Store linked node info
qualicen/specmate pull request #235
Opened 2021-01-14 15:24 UTC by sebeder

Closes #207

2021-01-18 10:10 UTC, wehrlean requested changes
If you delete a linking node and undo, the refs are not correct set again.

Create node
Create linked node
Delete the node
Undo
-> the linkednode has no reference to the node

2021-01-18 10:10 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/util/change-translator.ts
> +
remove empty line

2021-01-22 09:50 UTC, wehrlean requested changes
If you delete the linked node (CEGLinkedNode), the properties window still shows the properties of another node and not the properties of the model as usual.

2021-01-22 09:50 UTC, wehrlean commented on web/src/app/modules/forms/modules/validation/services/validation.service.ts
> +        // const contents = await this.dataService.readContents(element.url, true);
Remove line

2021-01-22 09:50 UTC, wehrlean commented on web/src/app/modules/forms/modules/validation/services/validation.service.ts
> +    constructor(private navigator: NavigatorService, private dataService: SpecmateDataService, translate: TranslateService) {
dataService is not used

2021-01-22 10:38 UTC, sebeder commented on web/src/app/modules/forms/modules/validation/services/validation.service.ts
> +        // const contents = await this.dataService.readContents(element.url, true);
Done

2021-01-22 10:38 UTC, sebeder commented on web/src/app/modules/forms/modules/validation/services/validation.service.ts
> +    constructor(private navigator: NavigatorService, private dataService: SpecmateDataService, translate: TranslateService) {
Removed

2021-01-22 11:51 UTC, wehrlean approved these changes
Except the imports it is fine

2021-01-22 11:51 UTC, wehrlean commented on web/src/app/modules/forms/modules/validation/services/validation.service.ts
> +import { SpecmateDataService } from 'src/app/modules/data/modules/data-service/services/specmate-data.service';
Remove unused imports

2021-01-22 11:53 UTC, sebeder commented on web/src/app/modules/forms/modules/validation/services/validation.service.ts
> +import { SpecmateDataService } from 'src/app/modules/data/modules/data-service/services/specmate-data.service';
Done - will this story ever end? ;-)

2021-01-22 11:53 UTC, merged