195 multiprojects
qualicen/specmate pull request #251
Opened 2021-01-27 15:38 UTC by hauptmab

Closes #195

2021-01-29 08:39 UTC, junkerm commented
if no projects (project.projects) are configured I get a NullPointerException: 
![grafik](https://user-images.githubusercontent.com/8638706/106251888-d6a67300-6215-11eb-9496-d4f37b997443.png)

2021-01-29 09:01 UTC, junkerm commented
If i configure the jira multiconnector and a regular jira connector (for the same jira isntance) none of the multiprojects are shown:  
![grafik](https://user-images.githubusercontent.com/8638706/106254412-f68b6600-6218-11eb-823b-8f59722160d2.png)

2021-01-29 09:02 UTC, junkerm commented
Is it already possible to configure libraries (e.g. via template)?

2021-02-02 10:21 UTC, junkerm reviewed
when i configure two multiproject for the same jira instance i get a nullpointer exception
![grafik](https://user-images.githubusercontent.com/8638706/106586418-b7c31c00-6548-11eb-9e51-16514edeee21.png)

2021-02-02 10:21 UTC, junkerm commented on bundles/specmate-connectors-api/src/com/specmate/connectors/api/IMultiConnector.java
> +	 * @return
remove empty @return

2021-02-02 10:21 UTC, junkerm commented on bundles/specmate-connectors-api/src/com/specmate/connectors/api/IMultiConnector.java
> +public interface IMultiConnector {
Please add short interface documentation

2021-02-02 10:21 UTC, junkerm commented on bundles/specmate-connectors-api/src/com/specmate/connectors/api/IMultiConnector.java
> +	 * Returns a list of project configs. Key is project id as it is known in the
list -> map

2021-02-02 12:25 UTC, junkerm requested changes
there are some small issues when no regular project is configured and when several multiprojects are configured (see comments) otherwiese just minor things

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/MultiConnectorService.java
> +@Component(immediate = true, configurationPid = MultiConnectorServiceConfig.PID, configurationPolicy = ConfigurationPolicy.REQUIRE)
please add a short documentation

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/MultiConnectorService.java
> +	}
you could add a @Deactivate method where you stop the schedular

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/MultiConnectorService.java
> +		public void run() {
format (or at leas remove empty lines)

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/MultiConnectorService.java
> +			List<String> configuredProjects = Arrays
would it make sense to retrieve the configured projects from the project service? What if a different multiconnectorservice is adding projects in parallel?

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/MultiProjectImpl.java
> +public class MultiProjectImpl implements IMultiProject {
please add short documentatino

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/config/MultiConnectorServiceConfig.java
> +public class MultiConnectorServiceConfig {
please add short documenation

2021-02-02 12:25 UTC, junkerm commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/JiraMultiConnector.java
> +						propertyKey.substring(JiraConfigConstants.KEY_JIRA_MULTIPROJECT_TEMPLATE_PREFIX.length()),
you could pull out the length() as variable at the start of the method

2021-02-03 09:24 UTC, hauptmab commented
> if no projects (project.projects) are configured I get a NullPointerException:
> ![grafik](https://user-images.githubusercontent.com/8638706/106251888-d6a67300-6215-11eb-9496-d4f37b997443.png)



> if no projects (project.projects) are configured I get a NullPointerException:
> ![grafik](https://user-images.githubusercontent.com/8638706/106251888-d6a67300-6215-11eb-9496-d4f37b997443.png)

fixed

2021-02-03 09:28 UTC, hauptmab commented
> If i configure the jira multiconnector and a regular jira connector (for the same jira isntance) none of the multiprojects are shown:
> ![grafik](https://user-images.githubusercontent.com/8638706/106254412-f68b6600-6218-11eb-823b-8f59722160d2.png)

@junkerm Is this the behaviour we talked about yesterday? Is it still not working?

2021-02-03 09:36 UTC, hauptmab commented
> Is it already possible to configure libraries (e.g. via template)?

this is handled in another issue: https://github.com/qualicen/specmate/issues/255

2021-02-04 12:11 UTC, hauptmab commented
> when i configure two multiproject for the same jira instance i get a nullpointer exception
> ![grafik](https://user-images.githubusercontent.com/8638706/106586418-b7c31c00-6548-11eb-9e51-16514edeee21.png)

This definitely was a bug. Fix already pushed.

2021-02-04 12:22 UTC, hauptmab commented on bundles/specmate-connectors/src/com/specmate/connectors/internal/MultiConnectorService.java
> +			List<String> configuredProjects = Arrays
Good point. However, during startup, it is not garanteed that all projects have already been created when the multi connectors will run the first time. Looking at the config will uncover projects which are not actived yet.

2021-02-04 13:07 UTC, junkerm commented
> 
> 
> > If i configure the jira multiconnector and a regular jira connector (for the same jira isntance) none of the multiprojects are shown:
> > ![grafik](https://user-images.githubusercontent.com/8638706/106254412-f68b6600-6218-11eb-823b-8f59722160d2.png)
> 
> @junkerm Is this the behaviour we talked about yesterday? Is it still not working?

it works now

2021-02-04 13:08 UTC, junkerm approved these changes

2021-02-04 14:07 UTC, merged