Negated ceg nodes dashed
qualicen/specmate pull request #26
Opened 2019-10-28 08:20 UTC by sebeder

This introduces a popup menu allowing for negating CEG connections.

2019-10-29 11:56 UTC, wehrlean requested changes
I like the popups, really nice
Some smaller and bigger issues:

- Two-way-binding with the negate-button doesn't work
- Style of the popup doesn't fit to the rest of Specmate, I think
- Clicking left on the label (variable or condition) of a node throws an error
- Add a new connection and then negate it twice leads to an error
- The popup stays on screen, if you open it and then switch the model 
- The other comments

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/shape-provider.ts
>              // tslint:disable-next-line:max-line-length
Remove linter-comment

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/shape-provider.ts
>              // tslint:disable-next-line:max-line-length
Remove linter-comment

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/util/change-translator.ts
>  import { type } from 'os';
Remove unused import

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/util/change-translator.ts
> +            }
Isn't _changeMade_ always false, thus the _.updateElement_ is never called?

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/graphical-editor.component.ts
> +    const invalidNodes = validationResult.filter(e => this.elementProvider.isNode(e.element));
Good to know, thanks :)

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/editor-components/editor-popup.ts
> +        menu.addItem('Delete', null, () => {
Add String to i18n

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/editor-components/editor-popup.ts
> +            menu.addItem('Negate', null, async () => {
Add String to i18n

2019-10-29 11:56 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/components/editor-components/editor-popup.ts
> +
Generally remove useless empty lines

2019-10-31 17:07 UTC, sebeder commented
I adressed all issues, but "the popup stays on screen...", because to realize this, we'd need a global reference to the popup and a global listener for click-events. Both is ugly and I'd suggest we live with this small glitch. OK?

2019-11-04 16:20 UTC, wehrlean approved these changes
Nice, everything works. Only one remark. At the beginning, I don't realize, that the circle and the checkmark is a kind of checkbox. Thus the 'negated' is a little bit confusing. Especially the 'delete' is a command and the 'negated' is a status. I expected 'negate' as a command.
And the popup-problem with new screen is no problem. This happens very rarely.

2019-11-05 10:10 UTC, merged