187 test generation for linked nodes
qualicen/specmate pull request #263
Opened 2021-02-14 17:23 UTC by junkerm

Closes #187

2021-02-15 06:17 UTC, sebeder requested changes
- You committed a folder `specmate-std-env/database2`. I think this should be removed.
- But otherwise, generation seems to work! Cool thing! ✔️

2021-02-15 06:17 UTC, sebeder commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/XrayServerExportService.java
> +			Thread.sleep(10000);
I don't understand, why we sleep here. Could you add a comment? And I think we can remove the comment below.

2021-02-15 06:17 UTC, sebeder commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/services/TestGeneratorService.java
> +			List<String> withLinksParams = queryParams.get("considerLinks");
Is the only reason to add the `MultivaluedMap` through all these methods to here, that we want to disable `considerLinks`? I think we should always consider the links anyways, or is there a scenario where this does not make sense?

2021-02-15 06:17 UTC, sebeder commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/CEGTestCaseGenerator.java
> +				Set<CEGNode> newNodes = getReachableNodes(linkedNode.getLinkTo());
I need to be honest here: I could not understand which set of nodes does what. Can this be done in an easier way? If not: Comments would be cool here.

2021-02-15 06:17 UTC, sebeder commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/CEGTestCaseGenerator.java
> +			CEGNode currentNode = workList.pop();
You, Sir, are the first person I see in this project, who really uses a stack! Cool! However, we should log a warning in case of cycles (in an `else` to `if`-statement below).

2021-02-15 06:17 UTC, sebeder commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/CEGTestCaseGenerator.java
> +			String condition = SpecmateEcoreUtil.getCondition(c).trim();
It is confusing that `CEGTestCaseGenerator.getCondition(...)` and `SpecmateEcoreUtil.getCondition(...)` are mixed. It might be better to use different method names.

2021-02-15 06:17 UTC, sebeder commented on web/src/app/modules/actions/modules/test-specification-generator-button/components/test-specification-generator-button.component.html
> +    <input class="form-check-input" type="checkbox" id="considerLinksCheck" [checked]="considerLinks" (change)="considerLinks=!considerLinks">
Is it possible to use `[(ngModel)]` for databinding here? You could omit the `(change)`-event then. So, instead of `[checked]=considerLinks`, you could try `[(ngModel)]=considerLinks` and omit the whole `(change)`-thing. But I do not know whether this works.

2021-02-15 06:17 UTC, sebeder commented on web/src/assets/i18n/gb.json
> +		"considerLinks": "Consider Linked Nodes",
I'd correct the casing to "Consider linked nodes".

2021-02-15 14:39 UTC, junkerm commented on bundles/specmate-jira-connector/src/com/specmate/connectors/jira/internal/services/XrayServerExportService.java
> +			Thread.sleep(10000);
done

2021-02-15 14:41 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/services/TestGeneratorService.java
> +			List<String> withLinksParams = queryParams.get("considerLinks");
it says so here: https://github.com/qualicen/specmate/issues/187

2021-02-15 14:49 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/CEGTestCaseGenerator.java
> +				Set<CEGNode> newNodes = getReachableNodes(linkedNode.getLinkTo());
I added comments, I don't know an easier way, do you have a suggestion?

2021-02-15 14:54 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/CEGTestCaseGenerator.java
> +			CEGNode currentNode = workList.pop();
Yes, however it's more a fifo queue as I add to the end and take from the front.
I added a warning log

2021-02-15 14:57 UTC, junkerm commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/generators/CEGTestCaseGenerator.java
> +			String condition = SpecmateEcoreUtil.getCondition(c).trim();
There is no CEGTestCaseGenerator.getCondition(...), but I made static imports of SpecmateEcoreUtil.getCondition(c), however inconsequent.  I fixed that.

2021-02-15 15:28 UTC, junkerm commented on web/src/app/modules/actions/modules/test-specification-generator-button/components/test-specification-generator-button.component.html
> +    <input class="form-check-input" type="checkbox" id="considerLinksCheck" [checked]="considerLinks" (change)="considerLinks=!considerLinks">
I tried this before, but it didn't work - when I check the checkbox the value is not propagated to the component field

2021-02-15 15:29 UTC, junkerm commented on web/src/assets/i18n/gb.json
> +		"considerLinks": "Consider Linked Nodes",
done

2021-02-16 04:56 UTC, sebeder commented on bundles/specmate-testspecification/src/com/specmate/testspecification/internal/services/TestGeneratorService.java
> +			List<String> withLinksParams = queryParams.get("considerLinks");
I see. Then, it's fine of course!

2021-02-16 04:58 UTC, sebeder approved these changes
Awesome! 😀😃😄😁

2021-02-16 05:03 UTC, merged