Added mxgraph type dropdown
qualicen/specmate pull request #27
Opened 2019-10-28 12:43 UTC by Daedo

2019-10-29 12:07 UTC, wehrlean requested changes
I am sorry for the work you spent in this feature, but it I think a more consequent way would be to use the popups implemented by @sebeder in PR #26 and add there a new item to change the type of the node. 
Your solution is more visible, but I think the popups are the better way. Should be discussed in the JF

2019-10-31 08:59 UTC, Daedo commented
After having discussed it we want to add it, since it is more visible.

2019-10-31 11:25 UTC, wehrlean requested changes
This way is definitive more visible. Two bugs:

- If you set the type to _OR_, save it and reload the page, the dropdown is set to _AND_ again
- Autolayout leads to an error, because the type is empty
- Remove tooltip for the dropdown (see trello)
- Comment

2019-10-31 11:25 UTC, wehrlean commented on web/src/app/modules/views/main/editors/modules/graphical-editor/providers/properties/vertex-provider.ts
>  import {VariableAndCondition} from '../../converters/variable-condition-name-converter';
Remove unused imports

2019-11-04 15:42 UTC, wehrlean approved these changes
Good, all things work!

2019-11-04 16:18 UTC, merged