Remove build warnings
qualicen/specmate pull request #364
Opened 2021-06-16 07:42 UTC by sebeder

Closes #

Maintenance - No issue.

2021-06-16 10:03 UTC, sebeder commented
Hi @wehrlean , I updated the dependencies as well.

2021-06-17 08:31 UTC, wehrlean requested changes
- Please adapt the Checks to newer Node Version
- And I am not sure, but it could be possible that you have to add `npm run extract` to the UI test building
- I get 'found 5 vulnerabilities (2 low, 2 moderate, 1 high)' if I run `npm run init`. Maybe you can check it

2021-06-17 08:31 UTC, wehrlean commented on web/src/app/modules/data/modules/data-service/services/specmate-data.service.ts
> +            x.charAt(100);
What the purpose of this?

2021-06-18 07:09 UTC, sebeder commented on web/src/app/modules/data/modules/data-service/services/specmate-data.service.ts
> +            x.charAt(100);
Oooooh, this will produce an error and I forgot to check that! Thanks! I need to work on this a little more...

2021-06-25 10:44 UTC, sebeder commented on web/src/app/modules/data/modules/data-service/services/specmate-data.service.ts
> +            x.charAt(100);
I just fixed that. Thank you for the hint, I really did not see this!

2021-06-28 08:21 UTC, wehrlean commented
I get `npm ERR! invalid bin entry for package @babel/parser@7.14.6. key=parser, value=bin/babel-parser.js` if I run `npm run init`. I am not sure if this is a problem on my computer or in general

2021-07-06 08:42 UTC, sebeder commented
> I get `npm ERR! invalid bin entry for package @babel/parser@7.14.6. key=parser, value=bin/babel-parser.js` if I run `npm run init`. I am not sure if this is a problem on my computer or in general

Hi @wehrlean , I did the following:

`npm cache clean --force`
`rm -rf node_modules`
`rm -rf package-lock.json`
`npm run init`

This should clean everything and work. Please tell me, if it does not.

2021-07-06 13:51 UTC, sebeder commented
Hi @wehrlean , I think this is a reviewable state. Could you please do that? Thank you!

2021-07-06 14:35 UTC, wehrlean requested changes
The installation works now. 
Some styling problems:
1. No spaces between the login buttons:
![image](https://user-images.githubusercontent.com/49229000/124616117-1b45d280-de76-11eb-9da3-ab0bba09a043.png)
2. Spaces right and left of mainbar
![image](https://user-images.githubusercontent.com/49229000/124616340-492b1700-de76-11eb-994a-a51987c0c26d.png)
3. The Icon and the field are not the same height
![image](https://user-images.githubusercontent.com/49229000/124616458-5f38d780-de76-11eb-974e-4836b9cf9720.png)
4. The space between labels and field is a little small. I think it need not that much space. (Maybe it is okay this way)
![image](https://user-images.githubusercontent.com/49229000/124616818-b179f880-de76-11eb-80fb-3dd2e6d0fce0.png)

2021-07-06 14:35 UTC, wehrlean commented on web/src/app/modules/data/modules/data-service/services/specmate-data.service.ts
> -            this.simpleModal.openOk(this.translate.instant('saveError.title'), this.translate.instant('saveError.retry'));
I think a warning to the user would be useful. Otherwise the changes get lost and the user does not even know it.

2021-07-07 10:18 UTC, sebeder commented
Hi @wehrlean , thank you! I addressed the issues Could you please review again?

2021-07-07 11:44 UTC, wehrlean requested changes

2021-07-07 11:44 UTC, wehrlean commented on web/src/app/modules/views/main/authentication/modules/choose-project/components/choose-project.component.html
> +  <input type="text" class="form-control form-control-sm" placeholder="Username" [(ngModel)]="project" [ngbTypeahead]="search"
Why is the placeholder "username" and use the translation module

2021-07-08 06:00 UTC, sebeder commented
OK, @wehrlean , that should do it. Thanks again for all the reviews. Could you do one more?

2021-07-08 08:20 UTC, wehrlean approved these changes
Sorry for my annoying accuracy... Now it's fine

2021-07-08 08:40 UTC, merged

2021-07-08 08:40 UTC, sebeder commented
That was not annoying! It's helpful! Thank you!