Translate Objectif into CEG
qualicen/specmate pull request #37
Opened 2019-11-05 15:22 UTC by fischJan

I already opened a pull request in our old repo and got feedback by max (see pull request #471):

1) match line breaks
2) add a sensible exception message that xtext parsing failed
3) enable umlauts
4) add "Sonst" effects to your grammar and visualize it within a CEG

all comments have been incorporated into the new commits

2019-11-27 15:12 UTC, tobi321 requested changes
Good job!
Works in old editor, merge develop into branch and check out if it still works with mx-graph. 
In old editor, all nodes are on the top left hiding each other. Is this the expected behaviour? 
Change the comments to multiline style (see below).

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-integration-test/src/com/specmate/test/integration/ObjectifTest.java
> +
Remove empty line

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-integration-test/src/com/specmate/test/integration/ObjectifTest.java
> +// Two types of tests:
Change the comment type to  /***/:
`/** Two types of tests:  1) tests for checking the functionality of the xtext parsing 2) tests for checking the functionality of the pseudo code translator */`

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/generated/buildfiles
> +A:/specmate/bundles/specmate-model-generation/generated/specmate-model-generation.jar
Do we need this buildfile?

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +// This class transforms pseudo code into a CEG.
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +	// This method creates a CEG model for each "WENN" --> "DANN" --> "ENDE-WENN"
Change to /** */ comment

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +		// The type of a BR node should be always "OR". Exception: The model consists
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +		// Check for nesting:
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +			// Basic idea: Split the whole tree in subtrees (i.e. split the tree into
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +			// that the rule contains another one and is therefore a condition for the
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +			// the inferior rule again. Until we reach a rule which is not nested anymore.
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +			// Case: not nested
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +			// 1. Case = The rule contains only one cause. This is the case if the rootCause
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +				// Create a node with the content of the rootCause and connect the node with the
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +//				if (rule.hasAlternative()) {
commented out code is duplicate of line 110-113. Remove.

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +				// 2. Case = The rule contains multiple causes which are interconnected
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +		// Iterate over all effects and connect the business rule node with these
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +				// a) there is only one set of conjunctive causes and no single / disjunctive
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +					// these nodes. All related causes share the same intermediate node!
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +		// We iterate over all single causes and connect them with the BR by means of a
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +	// Implementation for nested BRs:
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +	// Here we connect causes which are interconnected using conjunctions.
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +	// Here we separate between isolated causes (disjunctive causes) and related
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromPseudoCode.java
> +				// Here we identify a conjunction. We create a list of Objectif nodes for each
Change to /** Comment */

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromRequirementService.java
> +
Remove empty line

2019-11-27 15:12 UTC, tobi321 commented on bundles/specmate-model-generation/src/com/specmate/modelgeneration/GenerateModelFromRequirementService.java
> +
Remove empty line

2019-12-13 08:20 UTC, fischJan commented
> Good job!
> Works in old editor, merge develop into branch and check out if it still works with mx-graph.
> In old editor, all nodes are on the top left hiding each other. Is this the expected behaviour?
> Change the comments to multiline style (see below).

2019-12-18 08:57 UTC, tobi321 approved these changes
Good job!

2019-12-19 11:51 UTC, merged