Fix project explorer search
qualicen/specmate pull request #42
Opened 2019-11-21 11:41 UTC by tobi321

- Search bar in project explorer is sticky when scrolling
- Tabs in project explorer is sticky when scrolling
- If tab is selected it has a grey background

2019-11-22 13:00 UTC, wehrlean requested changes
Sadly it doesn't work properly.
- remove the bar if it is not needed
- the end of the bar is not on the right point -> see Screenshots on Trello
- on Firefox it doesn't work at all
- ~~search is not working, but I think that is another issue~~

2019-12-03 15:36 UTC, tobi321 commented
Tested on firefox and chrome

2019-12-04 09:58 UTC, wehrlean requested changes
It works, nice :) 
Only two small additions, see comments.

2019-12-04 09:58 UTC, wehrlean commented on web/src/app/modules/navigation/modules/project-explorer/components/project-explorer.component.css
> +    overflow: scroll;
Change overflow to 'auto'
Add 'height: 100%'

2019-12-04 09:58 UTC, wehrlean commented on web/src/app/modules/navigation/modules/project-explorer/components/project-explorer.component.html
> +    </table>
The result is not scrollable

2019-12-04 15:13 UTC, tobi321 commented
Search Results are now also scrollable with sticky 'Results' header.

2019-12-04 22:41 UTC, wehrlean approved these changes
Yeah, works fine!!!!

2019-12-05 06:36 UTC, merged